### ISSUE TITLE
ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by bartvollebregt** [muhk01/Yolov5-on-Flask#1]
Hi muhk01,

The project looks really good but I can't seem to get it working.
When running `python app.py` I get the following error:

``` 
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Users/my_user/.asdf/installs/python/3.8.5/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/my_user/.asdf/installs/python/3.8.5/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/my_user/IdeaProjects/Yolov5-on-Flask/base_camera.py", line 93, in _thread
    for frame in frames_iterator:
  File "/Users/my_user/IdeaProjects/Yolov5-on-Flask/camera.py", line 37, in frames
    model = torch.load(weights, map_location=device)['model']
  File "/Users/my_user/IdeaProjects/Yolov5-on-Flask/env/lib/python3.8/site-packages/torch/serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Users/my_user/IdeaProjects/Yolov5-on-Flask/env/lib/python3.8/site-packages/torch/serialization.py", line 842, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models'
``` 

I've used the following `requirements.txt` for the dependencies:
``` 
flask
numpy
opencv-python==4.1.2.30
torchvision
tqdm
matplotlib
scipy
``` 

What am I doing wrong?

**Comment by muhk01** [comment]
it is probably different version of torch, yolov5 require torch 1.5 equal or above.
try following requirements set as mentioned in yolov5 official requirements.txt
Cython
numpy==1.17
opencv-python
torch>=1.5
matplotlib
pillow
tensorboard
PyYAML>=5.3
torchvision
scipy
tqdm
git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI

**Comment by muhk01** [comment]
> Hi muhk01,
> 
> The project looks really good but I can't seem to get it working.
> When running `python app.py` I get the following error:
> 
> ```
> Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "/Users/my_user/.asdf/installs/python/3.8.5/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/Users/my_user/.asdf/installs/python/3.8.5/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Users/my_user/IdeaProjects/Yolov5-on-Flask/base_camera.py", line 93, in _thread
>     for frame in frames_iterator:
>   File "/Users/my_user/IdeaProjects/Yolov5-on-Flask/camera.py", line 37, in frames
>     model = torch.load(weights, map_location=device)['model']
>   File "/Users/my_user/IdeaProjects/Yolov5-on-Flask/env/lib/python3.8/site-packages/torch/serialization.py", line 584, in load
>     return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
>   File "/Users/my_user/IdeaProjects/Yolov5-on-Flask/env/lib/python3.8/site-packages/torch/serialization.py", line 842, in _load
>     result = unpickler.load()
> ModuleNotFoundError: No module named 'models'
> ```
> 
> I've used the following `requirements.txt` for the dependencies:
> 
> ```
> flask
> numpy
> opencv-python==4.1.2.30
> torchvision
> tqdm
> matplotlib
> scipy
> ```
> 
> What am I doing wrong?

i hope this not too late, apparently error produced because 'model' folder was not included, apparently this is my mistake because this folder project is merged with my current project and i only pull necessary folder and unfortunately miss 'model' folder, and also if you are using torch 1.6.0, you may replace this line
`for c in det[:, -1].unique():` 
became
`for c in det[:, -1].detach().unique():`
 this is actually a bug in torch 1.6.0 , while input is floating point that requires grad.
